--------------------------------------------------------------------------
-- FULGORA BOTTOM-UP OVERHAUL: INTERMEDIATES & DETRITUS
--------------------------------------------------------------------------

local item_sounds = require('__base__.prototypes.item_sounds')

data:extend {
    {
        type = 'item',
        name = 'metallic-slurry',
        icon = '__fulgora-scavenger-sovereign__/graphics/icons/metallic-slurry.png',
        icon_size = 1024,
        subgroup = 'fulgora-processes',
        order = 'b[dredging]-a[metallic-slurry]',
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 100,
        default_import_location = 'fulgora',
        weight = 1 * kg,
    },
    {
        type = 'item',
        name = 'mineral-silt',
        icon = '__fulgora-scavenger-sovereign__/graphics/icons/mineral-silt.png',
        icon_size = 1024,
        subgroup = 'fulgora-processes',
        order = 'b[dredging]-b[mineral-silt]',
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 100,
        default_import_location = 'fulgora',
        weight = 1 * kg,
    },
    {
        type = 'item',
        name = 'carbon-coke',
        icon = '__fulgora-scavenger-sovereign__/graphics/icons/carbon-coke.png',
        icon_size = 1024,
        fuel_value = '1.5MJ',
        fuel_category = 'chemical',
        subgroup = 'fulgora-processes',
        order = 'b[dredging]-c[carbon-coke]',
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 50,
        default_import_location = 'fulgora',
        weight = 1 * kg,
    },
    {
        type = 'item',
        name = 'silica-sand',
        icon = '__fulgora-scavenger-sovereign__/graphics/icons/silica-sand.png',
        icon_size = 1024,
        subgroup = 'fulgora-processes',
        order = 'c[solids]-a[silica-sand]',
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 100,
        default_import_location = 'fulgora',
        weight = 1 * kg,
    },
    {
        type = 'item',
        name = 'crushed-holmium',
        icon = '__fulgora-scavenger-sovereign__/graphics/icons/crushed-holmium.png',
        icon_size = 1024,
        subgroup = 'fulgora-processes',
        order = 'b[holmium]-b[crushed-holmium]',
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 50,
        default_import_location = 'fulgora',
        weight = 2 * kg,
    },
    {
        type = 'item',
        name = 'toxic-tar',
        icon = '__fulgora-scavenger-sovereign__/graphics/icons/toxic-tar.png',
        icon_size = 1024,
        fuel_value = '4MJ', -- High energy density but dirty
        fuel_category = 'chemical',
        fuel_emissions_multiplier = 3.5, -- Intense local pollution if burned!
        subgroup = 'fulgora-processes',
        order = 'b[dredging]-d[toxic-tar]',
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 50,
        default_import_location = 'fulgora',
        weight = 2 * kg,
    },
    {
        type = 'item',
        name = 'quartz-glass-plate',
        icon = '__fulgora-scavenger-sovereign__/graphics/icons/quartz-glass-plate.png',
        icon_size = 1024,
        subgroup = 'fulgora-processes',
        order = 'c[solids]-b[quartz-glass]',
        inventory_move_sound = item_sounds.metal_small_inventory_move,
        pick_sound = item_sounds.metal_small_inventory_pickup,
        drop_sound = item_sounds.metal_small_inventory_move,
        stack_size = 100,
        default_import_location = 'fulgora',
        weight = 500 * grams,
    },
    {
        type = 'item',
        name = 'insulated-arc-crucible',
        icon = '__fulgora-scavenger-sovereign__/graphics/icons/insulated-arc-crucible.png',
        icon_size = 1024,
        subgroup = 'fulgora-processes',
        order = 'd[advanced-components]-d[arc-crucible]',
        inventory_move_sound = item_sounds.mechanical_inventory_move,
        pick_sound = item_sounds.mechanical_inventory_pickup,
        drop_sound = item_sounds.mechanical_inventory_move,
        stack_size = 20,
        default_import_location = 'fulgora',
        weight = 5 * kg,
    },
}
